name: Build Docker images

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'

jobs:
  build_base:
    name: Build base image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: docker build --force-rm --rm --tag ghcr.io/isaac-gc/concrete-cms-docker:base ./base
      - name: Save base docker image
        run: docker save ghcr.io/isaac-gc/concrete-cms-docker:base | gzip > /tmp/base-image.tgz
      - name: Upload package
        uses: actions/upload-artifact@v3
        with: 
          name: base-image
          path: /tmp/base-image.tgz
      - name: Login to Github Container Repository
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish image
        run: docker push ghcr.io/isaac-gc/concrete-cms-docker:base

  build_images:
    name: Build Releaseable images
    runs-on: ubuntu-latest
    needs:
      - build_base
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download base image
        uses: actions/download-artifact@v3
        with:
          name: base-image
          path: /tmp/
      - name: Load base image
        run: docker load --input /tmp/base-image.tgz
      - name: Build and Tag Image - Concrete CMS 9.1.2
        run: |
          docker build --build-arg CCM_PHP_VERSION=9.1.2 --build-arg CCM_C5_ARCHIVE="https://github.com/concretecms/concretecms/archive/refs/tags/9.1.2.tar.gz" --tag ghcr.io/isaac-gc/concrete-cms-docker:9.1.2 ./release
      - name: Build and Tag Image - Concrete CMS 9.2.0
        run: |
            docker build --build-arg CCM_PHP_VERSION=9.2.0 --build-arg CCM_C5_ARCHIVE="https://github.com/concretecms/concretecms/archive/refs/tags/9.2.0.tar.gz" --tag ghcr.io/isaac-gc/concrete-cms-docker:9.2.0 ./release
      - name: Check that MariaDB works - Concrete CMS 9.1.2
        run: docker run --rm --entrypoint='' ghcr.io/isaac-gc/concrete-cms-docker:9.1.2 ccm-service start db
      - name: Check that MariaDB works - Concrete CMS 9.2.0
        run: docker run --rm --entrypoint='' ghcr.io/isaac-gc/concrete-cms-docker:9.2.0 ccm-service start db
      - name: Login to Github Container Repository
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish images
        run: |
            docker push ghcr.io/isaac-gc/concrete-cms-docker:9.1.2
            docker push ghcr.io/isaac-gc/concrete-cms-docker:9.2.0
            

